### ISSUE TITLE
Image rendered too large

### ISSUE THREAD

**Issue by onato** [dtorres/OLImageView#57]
With contentMode UIViewContentModeCenter…

    Aimv = [[OLImageView alloc] initWithImage:[OLImage imageNamed:@"google-io.gif"]];
    Aimv.contentMode = UIViewContentModeCenter;

…the image is rendered much larger than if using a UIImageView.

It seems that the scale of the image is not being accounted for. Any idea how I can work around this?

**Comment by dtorres** [comment]
I think this might be because the content is provided directly to the layer and it doesn't take into account any modes. 

See: https://github.com/ondalabs/OLImageView/blob/master/OLImageView.m#L175

Sadly, I don't have any workarounds for this nor the time to look into this further in the near future.
Any workarounds that you find or a PR to fix this are welcome.
